import type { ClozeItem } from '../types/grammar'

/**
 * JPST 100, Week 1 — です and の.
 *
 * Every sentence is built from Week 1 vocabulary and nothing else, so the drill
 * never asks a grammar question that is secretly a vocabulary question. All of
 * it is kana, for the same reason the vocabulary is (§11.2).
 *
 * Some sentences appear twice with the blank moved — わたしのなまえはフェリペです
 * is asked once for the の and once for the は. That is the point of a cloze: the
 * same sentence teaches a different thing depending on what is missing.
 */
export const WEEK1_CLOZE: ClozeItem[] = [
  {
    id: 'jpst100:w1:cloze:wa-topic',
    topic: 'desu',
    kind: 'particle',
    kana: 'わたし___がくせいです',
    answer: 'は',
    romaji: 'watashi wa gakusei desu',
    english: 'I am a student.',
    note: 'は marks the topic — and is pronounced wa, not ha, when it does.',
  },
  {
    id: 'jpst100:w1:cloze:desu-present',
    topic: 'desu',
    kind: 'copula',
    kana: 'わたしはがくせい___',
    answer: 'です',
    romaji: 'watashi wa gakusei desu',
    english: 'I am a student.',
    note: 'です is the polite copula, and it goes at the very end.',
  },
  {
    id: 'jpst100:w1:cloze:ka-question',
    topic: 'desu',
    kind: 'particle',
    kana: 'がくせいです___',
    answer: 'か',
    romaji: 'gakusei desu ka',
    english: 'Are you a student?',
    note: 'か makes it a question. Nothing else moves — no word order change.',
  },
  {
    id: 'jpst100:w1:cloze:deshita',
    topic: 'desu',
    kind: 'copula',
    kana: 'わたしはいちねんせい___',
    answer: 'でした',
    romaji: 'watashi wa ichinensei deshita',
    english: 'I was a first-year student.',
    note: 'でした is the past of です.',
  },
  {
    id: 'jpst100:w1:cloze:ja-nai-desu',
    topic: 'desu',
    kind: 'copula',
    kana: 'わたしはせんせい___',
    answer: 'じゃないです',
    romaji: 'watashi wa sensei ja nai desu',
    english: 'I am not a teacher.',
    note: 'The present negative. じゃ is the casual contraction of では.',
  },
  {
    id: 'jpst100:w1:cloze:ja-nakatta-desu',
    topic: 'desu',
    kind: 'copula',
    kana: 'わたしはにねんせい___',
    answer: 'じゃなかったです',
    romaji: 'watashi wa ninensei ja nakatta desu',
    english: 'I was not a second-year student.',
    note: 'The past negative — the negative and the past, both at once.',
  },
  {
    id: 'jpst100:w1:cloze:senkou-wa',
    topic: 'desu',
    kind: 'particle',
    kana: 'せんこう___にほんごです',
    answer: 'は',
    romaji: 'senkou wa nihongo desu',
    english: 'My major is Japanese.',
    note: 'は marks せんこう as the thing the sentence is about.',
  },
  {
    id: 'jpst100:w1:cloze:tomodachi-desu',
    topic: 'desu',
    kind: 'copula',
    kana: 'ともだちはブラジルじん___',
    answer: 'です',
    romaji: 'tomodachi wa burajiru-jin desu',
    english: 'My friend is Brazilian.',
    note: 'The same [Topic] は [Noun] です frame, with someone else as the topic.',
  },
  {
    id: 'jpst100:w1:cloze:no-possession',
    topic: 'no',
    kind: 'particle',
    kana: 'わたし___ほん',
    answer: 'の',
    romaji: 'watashi no hon',
    english: 'my book',
    note: 'の links two nouns: A の B is "A’s B". The owner comes first.',
  },
  {
    id: 'jpst100:w1:cloze:no-sensei-kuruma',
    topic: 'no',
    kind: 'particle',
    kana: 'せんせい___くるま',
    answer: 'の',
    romaji: 'sensei no kuruma',
    english: "the teacher's car",
    note: 'Same pattern, and no word changes shape to show possession.',
  },
  {
    id: 'jpst100:w1:cloze:no-category',
    topic: 'no',
    kind: 'particle',
    kana: 'にほんご___せんせいです',
    answer: 'の',
    romaji: 'nihongo no sensei desu',
    english: 'a Japanese teacher',
    note: 'の also links a category to a noun — literally "teacher of Japanese".',
  },
  {
    id: 'jpst100:w1:cloze:no-origin',
    topic: 'no',
    kind: 'particle',
    kana: 'カナダ___がくせいです',
    answer: 'の',
    romaji: 'kanada no gakusei desu',
    english: 'a Canadian student',
    note: 'Origin works the same way: "student of Canada".',
  },
  {
    id: 'jpst100:w1:cloze:no-chain',
    topic: 'no',
    kind: 'particle',
    kana: 'ともだちのいぬ___なまえ',
    answer: 'の',
    romaji: 'tomodachi no inu no namae',
    english: "my friend's dog's name",
    note: 'の chains. Read it right to left: the name, of the dog, of my friend.',
  },
  {
    id: 'jpst100:w1:cloze:no-pronoun',
    topic: 'no',
    kind: 'particle',
    kana: 'あかい___をください',
    answer: 'の',
    romaji: 'akai no o kudasai',
    english: 'Please give me the red one.',
    note: 'の can stand in for a noun already understood — English "one".',
  },
  {
    id: 'jpst100:w1:cloze:o-object',
    topic: 'no',
    kind: 'particle',
    kana: 'あかいの___ください',
    answer: 'を',
    romaji: 'akai no o kudasai',
    english: 'Please give me the red one.',
    note: 'を marks the object. Written wo, pronounced o.',
  },
  {
    id: 'jpst100:w1:cloze:namae-no',
    topic: 'no',
    kind: 'particle',
    kana: 'わたし___なまえはフェリペです',
    answer: 'の',
    romaji: 'watashi no namae wa feripe desu',
    english: 'My name is Felipe.',
    note: 'の for the owner, は for the topic — this sentence needs both.',
  },
  {
    id: 'jpst100:w1:cloze:namae-wa',
    topic: 'no',
    kind: 'particle',
    kana: 'わたしのなまえ___フェリペです',
    answer: 'は',
    romaji: 'watashi no namae wa feripe desu',
    english: 'My name is Felipe.',
    note: 'The same sentence, the other particle: わたしのなまえ is the topic.',
  },
]
